version: '3'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "H*aa550s!0gBfdE"
    ports:
      - "1433:1433"
  api:
    build: .
    ports:
      - "8080:80"